repos:
  - repo: https://github.com/uktrade/github-standards
    rev: v1.3.0
    hooks:
      - id: run-security-scan
        verbose: false
      - id: run-personal-data-scan
        verbose: false
      - id: validate-security-scan
        verbose: false
        
  - repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
    - id: ruff
    - id: ruff-format
